////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC
////

:figure-caption!:
:example-caption!:
:table-caption!:


[preface]
[#preface]
== Preface

As a reverse proxy server (also referred to as a gateway in HTTP RFCs), OpenIG filters all traffic to and from a server application, adapting requests to protect the service and adapting responses to filter outgoing content. The credential replay functionality effectively enables single sign-on (SSO) with applications that do not integrate easily into a traditional SSO service.
In reading and following the instructions in this guide, you will learn how to:

* Install OpenIG and evaluate all OpenIG features

* Protect server applications and integrate them with SSO solutions

* Use OpenIG to allow an existing application to act as an OAuth 2.0 resource server

* Use OpenIG to allow an existing application to act as an OAuth 2.0 client or OpenID Connect 1.0 Relying Party

* Use OpenIG to allow an existing application to act as a SAML 2.0 Service Provider

* Configure OpenIG to handle authentication in common use cases

* Monitor and audit traffic flowing through OpenIG

* Extend OpenIG with Groovy scripts and Java plugins

* Troubleshoot typical problems


[#d2528e221]
===  Using This Guide

This guide is intended for access management designers and administrators who develop, build, deploy, and maintain OpenIG for their organizations.
This guide is written so you can get started with OpenIG quickly, and learn more as you progress through the guide.
This guide is also written with the assumption that you already have basic familiarity with the following topics:

* Hypertext Transfer Protocol (HTTP), including how clients and servers exchange messages, and the role that a reverse proxy (gateway) plays

* JavaScript Object Notation (JSON), which is the format for OpenIG configuration files

* Managing services on operating systems and application servers

* Configuring network connections on operating systems

* Managing Public Key Infrastructure (PKI) used to establish HTTPS connections

* Access management for web applications

Depending on the features you use, you should also have basic familiarity with the following topics:

* Lightweight Directory Access Protocol (LDAP) if you use OpenIG with LDAP directory services

* Structured Query Language (SQL) if you use OpenIG with relational databases

* Configuring OpenAM if you use password capture and replay, or if you plan to follow the OAuth 2.0 or SAML 2.0 tutorials

* The Groovy programming language if you plan to extend OpenIG with scripts

* The Java programming language if you plan to extend OpenIG with plugins, and Apache Maven for building plugins

include::../partials/sec-formatting-conventions.adoc[]

include::../partials/sec-accessing-doc-online.adoc[]

include::../partials/sec-joining-the-community.adoc[]

include::../partials/sec-support-contact.adoc[]



