////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC
////

:figure-caption!:
:example-caption!:
:table-caption!:


[appendix]
[#appendix-interface-stability]
== Appendix A. Release Levels and Interface Stability

This appendix includes ForgeRock definitions for product release levels and interface stability.

[#release-levels]
=== A.1. ForgeRock Product Release Levels

ForgeRock defines Major, Minor, and Maintenance product release levels. The release level is reflected in the version number. The release level tells you what sort of compatibility changes to expect.
[#table-release-levels]
.Table A.1. Release Level Definitions
[cols="20%,20%,60%"]
|===
|Release Label |Version Numbers |Characteristics 

a|Major

a|Version: x[.0.0] (trailing 0s are optional)

a|
* Bring major new features, minor features, and bug fixes

* Can include changes even to Stable interfaces

* Can remove previously Deprecated functionality, and in rare cases remove Evolving functionality that has not been explicitly Deprecated

* Include changes present in previous Minor and Maintenance releases



a|Minor

a|Version: x.y[.0] (trailing 0s are optional)

a|
* Bring minor features, and bug fixes

* Can include backwards-compatible changes to Stable interfaces in the same Major release, and incompatible changes to Evolving interfaces

* Can remove previously Deprecated functionality

* Include changes present in previous Minor and Maintenance releases



a|Maintenance

a|Version: x.y.z

a|
* Bring bug fixes

* Are intended to be fully compatible with previous versions from the same Minor release


|===


[#interface-stability]
=== A.2. ForgeRock Product Interface Stability

ForgeRock products support many protocols, APIs, GUIs, and command-line interfaces. Some of these interfaces are standard and very stable. Others offer new functionality that is continuing to evolve.
ForgeRock acknowledges that you invest in these interfaces, and therefore must know when and how ForgeRock expects them to change. For that reason, ForgeRock defines interface stability labels and uses these definitions in ForgeRock products.
[#table-interface-stability]
.Table A.2. Interface Stability Definitions
[cols="25%,75%"]
|===
|Stability Label |Definition 

a|Stable

a|This documented interface is expected to undergo backwards-compatible changes only for major releases. Changes may be announced at least one minor release before they take effect.


a|Evolving

a|This documented interface is continuing to evolve and so is expected to change, potentially in backwards-incompatible ways even in a minor release. Changes are documented at the time of product release.
While new protocols and APIs are still in the process of standardization, they are Evolving. This applies for example to recent Internet-Draft implementations, and also to newly developed functionality.


a|Deprecated

a|This interface is deprecated and likely to be removed in a future release. For previously stable interfaces, the change was likely announced in a previous release. Deprecated interfaces will be removed from ForgeRock products.


a|Removed

a|This interface was deprecated in a previous release and has now been removed from the product.


a|Internal/Undocumented

a|Internal and undocumented interfaces can change without notice. If you depend on one of these interfaces, contact ForgeRock support or email link:mailto:info\@forgerock.com[info@forgerock.com, window=\_top] to discuss your needs.

|===


