FROM tomcat:9-jre8-alpine

MAINTAINER Open Identity Platform Community <open-identity-platform-openig@googlegroups.com>

ARG VERSION @project_version@

ENV CATALINA_HOME=/usr/local/tomcat
ENV OPENIG_USER="openig"
ENV OPENIG_BASE=/var/openig
ENV PATH=$CATALINA_HOME/bin:$PATH
ENV MEMORY="-server -XX:+UseG1GC -XX:+UseContainerSupport"
ENV CATALINA_OPTS="$MEMORY"

WORKDIR $CATALINA_HOME

RUN apk add --update --no-cache --virtual curl builddeps unzip bash && apk upgrade --update --no-cache \
 && rm -rf  $CATALINA_HOME/webapps/* \
 && curl -L https://github.com/OpenIdentityPlatform/OpenIG/releases/download/$VERSION/OpenIG-$VERSION.war --output $CATALINA_HOME/webapps/ROOT.war  \
 && adduser -S -u 1001 -G root $OPENIG_USER \
 && install -d -o $OPENIG_USER $OPENIG_BASE \
 && chown -R $OPENIG_USER $CATALINA_HOME/webapps \
 && apk del unzip && rm -rf /var/cache/apk/*

USER $OPENIG_USER

EXPOSE 8080 

HEALTHCHECK --interval=30s --timeout=30s --start-period=1s --retries=3 CMD curl -v -L --fail http://localhost:8080/openig/ || exit 1
 
CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]